var annotated_dup =
[
    [ "anonymous_namespace{main.mm}", "d8/d22/namespaceanonymous__namespace_02main_8mm_03.html", [
      [ "SdfToken", "d0/d86/structanonymous__namespace_02main_8mm_03_1_1_sdf_token.html", null ],
      [ "SdfNode", "d2/d21/structanonymous__namespace_02main_8mm_03_1_1_sdf_node.html", null ],
      [ "SdfTimingCheck", "db/d72/structanonymous__namespace_02main_8mm_03_1_1_sdf_timing_check.html", "db/d72/structanonymous__namespace_02main_8mm_03_1_1_sdf_timing_check" ],
      [ "SysTaskInfo", "df/d0a/structanonymous__namespace_02main_8mm_03_1_1_sys_task_info.html", null ],
      [ "FileHandleEntry", "de/d4a/structanonymous__namespace_02main_8mm_03_1_1_file_handle_entry.html", null ],
      [ "FileTable", "d1/dcf/structanonymous__namespace_02main_8mm_03_1_1_file_table.html", null ],
      [ "FormatSpec", "df/dd0/structanonymous__namespace_02main_8mm_03_1_1_format_spec.html", null ],
      [ "TimeFormatState", "db/dc1/structanonymous__namespace_02main_8mm_03_1_1_time_format_state.html", null ],
      [ "PackedSignalOffsets", "d4/d05/structanonymous__namespace_02main_8mm_03_1_1_packed_signal_offsets.html", null ],
      [ "PackedStateLayout", "d1/dc5/structanonymous__namespace_02main_8mm_03_1_1_packed_state_layout.html", null ],
      [ "DecodedServiceRecord", "d2/de9/structanonymous__namespace_02main_8mm_03_1_1_decoded_service_record.html", null ],
      [ "VcdSignal", "d5/dbb/structanonymous__namespace_02main_8mm_03_1_1_vcd_signal.html", null ],
      [ "VcdWriter", "dc/dfd/classanonymous__namespace_02main_8mm_03_1_1_vcd_writer.html", null ]
    ] ],
    [ "gpga", "da/d42/namespacegpga.html", [
      [ "anonymous_namespace{msl_codegen.cc}", "df/df8/namespacegpga_1_1anonymous__namespace_02msl__codegen_8cc_03.html", [
        [ "ConditionalStringBuf", "db/d93/classgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_conditional_string_buf.html", null ],
        [ "TaskSubst", "d9/d86/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_task_subst.html", null ],
        [ "SpecifyPathBlock", "df/dd6/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_specify_path_block.html", null ],
        [ "SystemTaskInfo", "dd/d0c/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_system_task_info.html", null ],
        [ "LvalueInfo", "d3/de7/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_lvalue_info.html", null ],
        [ "SchedulerVmProcDef", "d0/d8a/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_scheduler_vm_proc_def.html", null ],
        [ "SchedulerVmServiceCall", "d8/d44/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_scheduler_vm_service_call.html", null ],
        [ "SchedulerVmTables", "d5/dda/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_scheduler_vm_tables.html", null ],
        [ "SchedulerVmCrossProcPatch", "d0/d58/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_scheduler_vm_cross_proc_patch.html", null ],
        [ "SchedulerVmContext", "db/d5a/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_scheduler_vm_context.html", null ],
        [ "SchedulerVmPatch", "da/d30/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_scheduler_vm_patch.html", null ],
        [ "SchedulerVmCaseTableData", "d8/d63/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_scheduler_vm_case_table_data.html", null ],
        [ "SchedulerVmPackedSignalSlot", "d0/df2/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_scheduler_vm_packed_signal_slot.html", null ],
        [ "SchedulerVmExprEmitContext", "df/d99/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_scheduler_vm_expr_emit_context.html", null ],
        [ "SchedulerVmEmitter", "d4/d88/structgpga_1_1anonymous__namespace_02msl__codegen_8cc_03_1_1_scheduler_vm_emitter.html", null ]
      ] ],
      [ "anonymous_namespace{elaboration.cc}", "d7/d27/namespacegpga_1_1anonymous__namespace_02elaboration_8cc_03.html", [
        [ "PortBinding", "dd/dca/structgpga_1_1anonymous__namespace_02elaboration_8cc_03_1_1_port_binding.html", null ],
        [ "ParamBindings", "d5/d7e/structgpga_1_1anonymous__namespace_02elaboration_8cc_03_1_1_param_bindings.html", null ],
        [ "ConstVar", "d3/dc0/structgpga_1_1anonymous__namespace_02elaboration_8cc_03_1_1_const_var.html", null ],
        [ "ConstScope", "d3/dde/structgpga_1_1anonymous__namespace_02elaboration_8cc_03_1_1_const_scope.html", null ],
        [ "SymbolicVar", "d6/daa/structgpga_1_1anonymous__namespace_02elaboration_8cc_03_1_1_symbolic_var.html", null ],
        [ "SignalRef", "d8/dce/structgpga_1_1anonymous__namespace_02elaboration_8cc_03_1_1_signal_ref.html", null ]
      ] ],
      [ "anonymous_namespace{verilog_parser.cc}", "da/dfb/namespacegpga_1_1anonymous__namespace_02verilog__parser_8cc_03.html", [
        [ "Token", "d8/d7d/structgpga_1_1anonymous__namespace_02verilog__parser_8cc_03_1_1_token.html", null ],
        [ "MacroDef", "d5/da0/structgpga_1_1anonymous__namespace_02verilog__parser_8cc_03_1_1_macro_def.html", null ],
        [ "IfdefState", "d0/dd0/structgpga_1_1anonymous__namespace_02verilog__parser_8cc_03_1_1_ifdef_state.html", null ],
        [ "DirectiveEvent", "d5/d57/structgpga_1_1anonymous__namespace_02verilog__parser_8cc_03_1_1_directive_event.html", null ],
        [ "Parser", "d8/dd5/classgpga_1_1anonymous__namespace_02verilog__parser_8cc_03_1_1_parser.html", null ]
      ] ],
      [ "SchedulerVmExprFeatures", "d1/dc2/structgpga_1_1_scheduler_vm_expr_features.html", "d1/dc2/structgpga_1_1_scheduler_vm_expr_features" ],
      [ "SchedulerVmAssignFallbackInfo", "df/da9/structgpga_1_1_scheduler_vm_assign_fallback_info.html", "df/da9/structgpga_1_1_scheduler_vm_assign_fallback_info" ],
      [ "SchedulerVmServiceFallbackInfo", "df/d8b/structgpga_1_1_scheduler_vm_service_fallback_info.html", "df/d8b/structgpga_1_1_scheduler_vm_service_fallback_info" ],
      [ "SchedulerVmFallbackDiagnostics", "d6/d60/structgpga_1_1_scheduler_vm_fallback_diagnostics.html", "d6/d60/structgpga_1_1_scheduler_vm_fallback_diagnostics" ],
      [ "MslEmitOptions", "d0/d11/structgpga_1_1_msl_emit_options.html", "d0/d11/structgpga_1_1_msl_emit_options" ],
      [ "ElaboratedDesign", "d2/d6b/structgpga_1_1_elaborated_design.html", "d2/d6b/structgpga_1_1_elaborated_design" ],
      [ "SchedulerVmExprTable", "d8/d70/structgpga_1_1_scheduler_vm_expr_table.html", "d8/d70/structgpga_1_1_scheduler_vm_expr_table" ],
      [ "SchedulerVmCondEntry", "d1/d18/structgpga_1_1_scheduler_vm_cond_entry.html", "d1/d18/structgpga_1_1_scheduler_vm_cond_entry" ],
      [ "SchedulerVmPackedSlot", "d7/d41/structgpga_1_1_scheduler_vm_packed_slot.html", "d7/d41/structgpga_1_1_scheduler_vm_packed_slot" ],
      [ "SchedulerVmSignalEntry", "d0/d2b/structgpga_1_1_scheduler_vm_signal_entry.html", "d0/d2b/structgpga_1_1_scheduler_vm_signal_entry" ],
      [ "SchedulerVmCaseHeader", "da/d7d/structgpga_1_1_scheduler_vm_case_header.html", "da/d7d/structgpga_1_1_scheduler_vm_case_header" ],
      [ "SchedulerVmCaseEntry", "de/d83/structgpga_1_1_scheduler_vm_case_entry.html", "de/d83/structgpga_1_1_scheduler_vm_case_entry" ],
      [ "SchedulerVmAssignEntry", "d0/d78/structgpga_1_1_scheduler_vm_assign_entry.html", "d0/d78/structgpga_1_1_scheduler_vm_assign_entry" ],
      [ "SchedulerVmDelayAssignEntry", "de/da7/structgpga_1_1_scheduler_vm_delay_assign_entry.html", "de/da7/structgpga_1_1_scheduler_vm_delay_assign_entry" ],
      [ "SchedulerVmForceEntry", "de/d88/structgpga_1_1_scheduler_vm_force_entry.html", "de/d88/structgpga_1_1_scheduler_vm_force_entry" ],
      [ "SchedulerVmReleaseEntry", "d0/de6/structgpga_1_1_scheduler_vm_release_entry.html", "d0/de6/structgpga_1_1_scheduler_vm_release_entry" ],
      [ "SchedulerVmServiceEntry", "d9/d41/structgpga_1_1_scheduler_vm_service_entry.html", "d9/d41/structgpga_1_1_scheduler_vm_service_entry" ],
      [ "SchedulerVmServiceArg", "df/ddb/structgpga_1_1_scheduler_vm_service_arg.html", "df/ddb/structgpga_1_1_scheduler_vm_service_arg" ],
      [ "SchedulerVmServiceRetAssignEntry", "da/d19/structgpga_1_1_scheduler_vm_service_ret_assign_entry.html", "da/d19/structgpga_1_1_scheduler_vm_service_ret_assign_entry" ],
      [ "SchedulerVmLayout", "df/dc6/structgpga_1_1_scheduler_vm_layout.html", "df/dc6/structgpga_1_1_scheduler_vm_layout" ],
      [ "SchedulerVmBuilder", "dc/d12/classgpga_1_1_scheduler_vm_builder.html", "dc/d12/classgpga_1_1_scheduler_vm_builder" ],
      [ "SchedulerVmExprBuilder", "de/d5e/classgpga_1_1_scheduler_vm_expr_builder.html", "de/d5e/classgpga_1_1_scheduler_vm_expr_builder" ],
      [ "Port", "d9/d28/structgpga_1_1_port.html", "d9/d28/structgpga_1_1_port" ],
      [ "Switch", "d9/d2e/structgpga_1_1_switch.html", "d9/d2e/structgpga_1_1_switch" ],
      [ "ArrayDim", "d8/d2d/structgpga_1_1_array_dim.html", "d8/d2d/structgpga_1_1_array_dim" ],
      [ "Net", "d3/d89/structgpga_1_1_net.html", "d3/d89/structgpga_1_1_net" ],
      [ "Expr", "d0/d77/structgpga_1_1_expr.html", "d0/d77/structgpga_1_1_expr" ],
      [ "Parameter", "d3/dbf/structgpga_1_1_parameter.html", "d3/dbf/structgpga_1_1_parameter" ],
      [ "FunctionArg", "d5/d7e/structgpga_1_1_function_arg.html", "d5/d7e/structgpga_1_1_function_arg" ],
      [ "LocalVar", "dd/d74/structgpga_1_1_local_var.html", "dd/d74/structgpga_1_1_local_var" ],
      [ "Function", "de/de7/structgpga_1_1_function.html", "de/de7/structgpga_1_1_function" ],
      [ "Assign", "da/d79/structgpga_1_1_assign.html", "da/d79/structgpga_1_1_assign" ],
      [ "SequentialAssign", "d4/d28/structgpga_1_1_sequential_assign.html", "d4/d28/structgpga_1_1_sequential_assign" ],
      [ "TimingEdgePattern", "d9/d74/structgpga_1_1_timing_edge_pattern.html", "d9/d74/structgpga_1_1_timing_edge_pattern" ],
      [ "TimingCheckLimit", "db/d27/structgpga_1_1_timing_check_limit.html", "db/d27/structgpga_1_1_timing_check_limit" ],
      [ "TimingCheckEvent", "dc/dee/structgpga_1_1_timing_check_event.html", "dc/dee/structgpga_1_1_timing_check_event" ],
      [ "EventItem", "dc/d49/structgpga_1_1_event_item.html", "dc/d49/structgpga_1_1_event_item" ],
      [ "CaseItem", "d4/d5a/structgpga_1_1_case_item.html", "d4/d5a/structgpga_1_1_case_item" ],
      [ "Statement", "d6/d42/structgpga_1_1_statement.html", "d6/d42/structgpga_1_1_statement" ],
      [ "AlwaysBlock", "db/d59/structgpga_1_1_always_block.html", "db/d59/structgpga_1_1_always_block" ],
      [ "TaskArg", "d7/d5b/structgpga_1_1_task_arg.html", "d7/d5b/structgpga_1_1_task_arg" ],
      [ "Task", "dd/d77/structgpga_1_1_task.html", "dd/d77/structgpga_1_1_task" ],
      [ "EventDecl", "d9/d5c/structgpga_1_1_event_decl.html", "d9/d5c/structgpga_1_1_event_decl" ],
      [ "Connection", "d8/d37/structgpga_1_1_connection.html", "d8/d37/structgpga_1_1_connection" ],
      [ "ParamOverride", "dc/d00/structgpga_1_1_param_override.html", "dc/d00/structgpga_1_1_param_override" ],
      [ "Instance", "d9/db8/structgpga_1_1_instance.html", "d9/db8/structgpga_1_1_instance" ],
      [ "DefParam", "d0/d43/structgpga_1_1_def_param.html", "d0/d43/structgpga_1_1_def_param" ],
      [ "TimingCheck", "d6/db0/structgpga_1_1_timing_check.html", "d6/db0/structgpga_1_1_timing_check" ],
      [ "PathPulseSpec", "d7/d2d/structgpga_1_1_path_pulse_spec.html", "d7/d2d/structgpga_1_1_path_pulse_spec" ],
      [ "SpecifyPath", "d9/d9e/structgpga_1_1_specify_path.html", "d9/d9e/structgpga_1_1_specify_path" ],
      [ "Module", "d4/d32/structgpga_1_1_module.html", "d4/d32/structgpga_1_1_module" ],
      [ "Program", "d3/dfe/structgpga_1_1_program.html", "d3/dfe/structgpga_1_1_program" ],
      [ "FourStateValue", "d5/d29/structgpga_1_1_four_state_value.html", "d5/d29/structgpga_1_1_four_state_value" ],
      [ "ParseOptions", "d3/dad/structgpga_1_1_parse_options.html", "d3/dad/structgpga_1_1_parse_options" ],
      [ "ServiceStringTable", "d7/d14/structgpga_1_1_service_string_table.html", "d7/d14/structgpga_1_1_service_string_table" ],
      [ "ServiceArgView", "d3/ddf/structgpga_1_1_service_arg_view.html", "d3/ddf/structgpga_1_1_service_arg_view" ],
      [ "ServiceRecordView", "dc/dcd/structgpga_1_1_service_record_view.html", "dc/dcd/structgpga_1_1_service_record_view" ],
      [ "ServiceDrainResult", "d8/d5c/structgpga_1_1_service_drain_result.html", "d8/d5c/structgpga_1_1_service_drain_result" ],
      [ "GpgaParams", "d3/dda/structgpga_1_1_gpga_params.html", "d3/dda/structgpga_1_1_gpga_params" ],
      [ "GpgaSchedParams", "d9/d2b/structgpga_1_1_gpga_sched_params.html", "d9/d2b/structgpga_1_1_gpga_sched_params" ],
      [ "SignalInfo", "d6/dbb/structgpga_1_1_signal_info.html", "d6/dbb/structgpga_1_1_signal_info" ],
      [ "ModuleInfo", "d3/d15/structgpga_1_1_module_info.html", "d3/d15/structgpga_1_1_module_info" ],
      [ "SchedulerConstants", "d1/dc4/structgpga_1_1_scheduler_constants.html", "d1/dc4/structgpga_1_1_scheduler_constants" ],
      [ "BufferSpec", "dc/d7d/structgpga_1_1_buffer_spec.html", "dc/d7d/structgpga_1_1_buffer_spec" ],
      [ "MetalBuffer", "d8/dc6/classgpga_1_1_metal_buffer.html", "d8/dc6/classgpga_1_1_metal_buffer" ],
      [ "MetalBufferBinding", "d3/dcc/structgpga_1_1_metal_buffer_binding.html", "d3/dcc/structgpga_1_1_metal_buffer_binding" ],
      [ "MetalDispatch", "df/d62/structgpga_1_1_metal_dispatch.html", "df/d62/structgpga_1_1_metal_dispatch" ],
      [ "MetalKernel", "d5/dd0/classgpga_1_1_metal_kernel.html", "d5/dd0/classgpga_1_1_metal_kernel" ],
      [ "MetalRuntime", "de/d65/classgpga_1_1_metal_runtime.html", "de/d65/classgpga_1_1_metal_runtime" ],
      [ "SourceStats", "dd/d7c/structgpga_1_1_source_stats.html", null ],
      [ "FunctionStats", "dc/df5/structgpga_1_1_function_stats.html", null ],
      [ "SourceLocation", "dd/dc0/structgpga_1_1_source_location.html", "dd/dc0/structgpga_1_1_source_location" ],
      [ "Diagnostic", "de/d93/structgpga_1_1_diagnostic.html", "de/d93/structgpga_1_1_diagnostic" ],
      [ "Diagnostics", "dc/dc7/classgpga_1_1_diagnostics.html", "dc/dc7/classgpga_1_1_diagnostics" ]
    ] ],
    [ "GPGA_2STATE_SIM", "df/d0a/namespace_g_p_g_a__2_s_t_a_t_e___s_i_m.html", [
      [ "Wires_2State", "d0/dd5/struct_g_p_g_a__2_s_t_a_t_e___s_i_m_1_1_wires__2_state.html", "d0/dd5/struct_g_p_g_a__2_s_t_a_t_e___s_i_m_1_1_wires__2_state" ]
    ] ],
    [ "GPGA_4STATE_SIM", "da/dc7/namespace_g_p_g_a__4_s_t_a_t_e___s_i_m.html", [
      [ "Wires_4State", "d1/dbf/struct_g_p_g_a__4_s_t_a_t_e___s_i_m_1_1_wires__4_state.html", "d1/dbf/struct_g_p_g_a__4_s_t_a_t_e___s_i_m_1_1_wires__4_state" ]
    ] ],
    [ "Simulator", "d0/d04/namespace_simulator.html", [
      [ "Wires_2State", "d7/d8c/struct_simulator_1_1_wires__2_state.html", "d7/d8c/struct_simulator_1_1_wires__2_state" ],
      [ "Wires_4State", "dc/dd8/struct_simulator_1_1_wires__4_state.html", "dc/dd8/struct_simulator_1_1_wires__4_state" ]
    ] ],
    [ "BinarySpec", "d2/d45/struct_binary_spec.html", null ],
    [ "CompareStats", "da/da0/struct_compare_stats.html", null ],
    [ "FourState32", "d4/d30/struct_four_state32.html", "d4/d30/struct_four_state32" ],
    [ "FourState64", "dd/d12/struct_four_state64.html", "dd/d12/struct_four_state64" ],
    [ "gpga_rrinfo", "d8/dd0/structgpga__rrinfo.html", null ],
    [ "GpgaDd", "df/d0f/struct_gpga_dd.html", null ],
    [ "GpgaExpTableEntry", "d8/d1b/struct_gpga_exp_table_entry.html", null ],
    [ "GpgaLogArgRedEntry", "df/df7/struct_gpga_log_arg_red_entry.html", null ],
    [ "GpgaPowArgRed", "dd/dd1/struct_gpga_pow_arg_red.html", null ],
    [ "GpgaPowTwoPowerIndex1", "d2/d26/struct_gpga_pow_two_power_index1.html", null ],
    [ "GpgaPowTwoPowerIndex2", "d2/d46/struct_gpga_pow_two_power_index2.html", null ],
    [ "GpgaSchedParams", "dc/d29/struct_gpga_sched_params.html", "dc/d29/struct_gpga_sched_params" ],
    [ "GpgaSchedVmAssignEntry", "da/db2/struct_gpga_sched_vm_assign_entry.html", "da/db2/struct_gpga_sched_vm_assign_entry" ],
    [ "GpgaSchedVmCaseEntry", "d2/d9e/struct_gpga_sched_vm_case_entry.html", "d2/d9e/struct_gpga_sched_vm_case_entry" ],
    [ "GpgaSchedVmCaseHeader", "d3/d6d/struct_gpga_sched_vm_case_header.html", "d3/d6d/struct_gpga_sched_vm_case_header" ],
    [ "GpgaSchedVmCondEntry", "de/d57/struct_gpga_sched_vm_cond_entry.html", "de/d57/struct_gpga_sched_vm_cond_entry" ],
    [ "GpgaSchedVmDelayAssignEntry", "d7/d73/struct_gpga_sched_vm_delay_assign_entry.html", "d7/d73/struct_gpga_sched_vm_delay_assign_entry" ],
    [ "GpgaSchedVmForceEntry", "d6/ded/struct_gpga_sched_vm_force_entry.html", "d6/ded/struct_gpga_sched_vm_force_entry" ],
    [ "GpgaSchedVmReleaseEntry", "dc/dca/struct_gpga_sched_vm_release_entry.html", "dc/dca/struct_gpga_sched_vm_release_entry" ],
    [ "GpgaSchedVmServiceArg", "d1/d1b/struct_gpga_sched_vm_service_arg.html", "d1/d1b/struct_gpga_sched_vm_service_arg" ],
    [ "GpgaSchedVmServiceEntry", "d9/daa/struct_gpga_sched_vm_service_entry.html", "d9/daa/struct_gpga_sched_vm_service_entry" ],
    [ "GpgaSchedVmServiceRetAssignEntry", "d8/d19/struct_gpga_sched_vm_service_ret_assign_entry.html", "d8/d19/struct_gpga_sched_vm_service_ret_assign_entry" ],
    [ "GpgaSchedVmSignalEntry", "d5/d4d/struct_gpga_sched_vm_signal_entry.html", "d5/d4d/struct_gpga_sched_vm_signal_entry" ],
    [ "GpgaTd", "dc/d67/struct_gpga_td.html", null ],
    [ "GpgaTrigpiEntry", "d6/de2/struct_gpga_trigpi_entry.html", null ],
    [ "scs", "dc/df2/structscs.html", "dc/df2/structscs" ],
    [ "UnarySpec", "da/d4f/struct_unary_spec.html", null ]
];